image: Visual Studio 2019

build_script:
  - dotnet build %solution_name%
test_script:
  - dotnet test %solution_name%
image: Visual Studio 2019

before_build:
  - ps: |
      $solutuon = "AutomataConstructor/AutomataConstructor.sln"
      nuget restore $solution
build_script:
  - ps: |
      dotnet build $solution
test_script:
  - ps: |
      dotnet test $solution