image: Visual Studio 2019
before_build:
  $solutuon_name = "AutomataConstructor/AutomataConstructor.sln"
  - nuget restore 

build_script:
  - dotnet build %solution_name%
test_script:
  - dotnet test %solution_name%